---
title: "The relative age effect in international biathlon"
author: "Andreas K. Winther"
date: "1/31/2020"
output: word_document
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
The relative age effect (RAE) refers to an asymmetry in the birth-date distribution, with an over-representation of those born at the beginning of the competitive year and an under-representation of those born
at the end (@delorme2010relative. Although @baker2014variations found this effect in a handful of winter sports at the elite level, no studies have examined whether the same pattern holds true across different levels of biathlon. Thus, the aim of the present study was to investigated whether RAEs exist at different levels of competition in international biathlon.      

## Methods
Data was obtained by scraping the official standings for both the men's and women's Junior Cup, IBU Cup, and World Cup, over the last five competitive seasons (2015/2016 - 2019/2020). This resulted in a sample of 303 women and 307 men at the junior level, 325 women and 340 men at the IBU level, and 173 women and 163 men at the World Cup level. Athletes were categorized into four quarters based on their birth month (i.e., Q1 = January to March; Q2 = April to June; Q3: July to September; and Q4: October to December). Differences among relative age quartiles were considered using a chi-square goodness-of-fit test ($\chi^2$) against an assumed equal distribution. Odds ratios (+- 95% confidence intervals) was also calculated, using Q1 as reference.    

## Results
Chi-square testing revealed a significant overall effect ($\chi^2$ = 9.58, p < 0.05) in the Junior Cup, but not in the IBU Cup ($\chi^2$ = 4.53, p = 0.21) or the World Cup ($\chi^2$ = 4.69, p = 0.20). When men and women were considered separately, the effect persisted for the women's Junior Cup ($\chi^2$ = 10.54, p = 0.01). Odds ratios revealed that women and men born in Q1 had 2.0 (95% CI: 1.39 - 3.00) and 1.5 (95% CI: 1.13 - 2.38) times the odds of competing in the Junior Cup compared to athletes born in Q4. For the women's IBU Cup, athletes born in Q1 had 1.5 (95% CI: 1.05 - 2.14) times the odds of competing compared to athletes born in Q3.    

## Conclusion
Birth date has a relevant influence on participation in biathlon, particularly at the junior international level. As such, a much larger percentage of women athletes at junior level were born in the first quartile compared to the last quartile. Overall, these findings seem to indicate a deleterious impact of the RAE for the relatively younger. Although, this effect also seem to diminish to some degree at higher levels of competition.

## References